// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared;

public partial class Flightpath
{
    public int Id { get; set; }

    public decimal Fare { get; set; }

    public bool Luggage { get; set; }

    public int OutboundFlightId { get; set; }

    public int HomeboundFlightId { get; set; }

    public int TravelPackageId { get; set; }

    public virtual Flight HomeboundFlight { get; set; }

    public virtual Flight OutboundFlight { get; set; }

    public virtual TravelPackage TravelPackage { get; set; }
}