// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared;

public partial class Flight
{
    public int Id { get; set; }

    public DateTime DepartureTime { get; set; }

    public DateTime ArrivalTime { get; set; }

    public int IatadestinationId { get; set; }

    public int IataoriginId { get; set; }

    public virtual ICollection<Flightpath> FlightpathHomeboundFlights { get; set; } = new List<Flightpath>();

    public virtual ICollection<Flightpath> FlightpathOutboundFlights { get; set; } = new List<Flightpath>();

    public virtual IataLocation Iatadestination { get; set; }

    public virtual IataLocation Iataorigin { get; set; }
}