// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared1;

public partial class TravelPackage
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int HotelId { get; set; }

    public virtual ICollection<Flightpath> Flightpaths { get; set; } = new List<Flightpath>();

    public virtual Hotel Hotel { get; set; }
}