// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared;

// vores TravelPackage model
public partial class TravelPackage
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public ICollection<Flightpath> Flightpaths { get; set; } = new List<Flightpath>();

    public Hotel Hotel { get; set; }
}


// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
public partial class TravelPackage
{
    public virtual int HotelId { get; set; }
}