// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shared1;

public partial class VwFlight
{
    public int Id { get; set; }

    public DateTime DepartureTime { get; set; }

    public DateTime ArrivalTime { get; set; }

    public string Destination { get; set; }

    public string Origin { get; set; }

    public string IataDestination { get; set; }

    public string IataOrigin { get; set; }
}