// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Antiforgery;
using System;
using System.Collections.Generic;

namespace Gotorz14.Models;

public partial class Flight
{
    public int Id { get; set; }

    public virtual Flightpath Flightpath { get; set; } = null!;

    public DateTime DepartureTime { get; set; }

    public DateTime ArrivalTime { get; set; }

    public string Destination { get; set; }

    public string Origin { get; set; }

    public string IataDestination { get; set; }

    public string IataOrigin { get; set; }
}