// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;

namespace Gotorz14.Models;

public partial class Flightpath
{
    public int Id { get; set; }

    public decimal Fare { get; set; }

    public bool Luggage { get; set; }

    public ICollection<Flight> Flights { get; set; }

    public Flight Outbound =>  !Flights.IsNullOrEmpty() ? Flights.FirstOrDefault() : null;
    public Flight Homebound => !Flights.IsNullOrEmpty() ? Flights.LastOrDefault() : null;

    public int TravelPackageId { get; set; }
    public virtual TravelPackage TravelPackage { get; set; }
}