// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gotorz14.Models;

public partial class Hotel
{
    public int Id { get; set; }

    public DateTime CheckIn { get; set; }

    public DateTime CheckOut { get; set; }

    public decimal Rate { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Telephonenumber { get; set; }

    public string Email { get; set; }

    public string Description { get; set; }

    public virtual ICollection<TravelPackage> TravelPackages { get; set; } = new List<TravelPackage>();
}