// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedLib;


// vores IataLocation model
public partial class IataLocation
{
    public int Id { get; set; }

    public string Iata { get; set; }

    public string City { get; set; }

}

public partial class IataLocation
{
    [JsonIgnore]
    public virtual ICollection<Flight> FlightIatadestinations { get; set; } = new List<Flight>();

    [JsonIgnore]
    public virtual ICollection<Flight> FlightIataorigins { get; set; } = new List<Flight>();
}