using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SharedLib;

// vores TravelPackage model
public partial class TravelPackage
{
    public int Id { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    [CustomValidation(typeof(TravelPackageValidator), "ValidateFlightpaths")]
    public ICollection<Flightpath> Flightpaths { get; set; } = new List<Flightpath>();

    [Required]
    public Hotel Hotel { get; set; }

    public Photo? Photo { get; set; }
}

public static class TravelPackageValidator
{
    public static ValidationResult? ValidateFlightpaths(ICollection<Flightpath>? flightpaths, ValidationContext context)
    {
        if (flightpaths == null || flightpaths.Count == 0)
        {
            return new ValidationResult("Flightpaths collection cannot be null or empty.", new[] { nameof(flightpaths) });
        }

        return ValidationResult.Success;
    }
}

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
public partial class TravelPackage
{
    [JsonIgnore]
    public virtual int HotelId { get; set; }

    [JsonIgnore]
    public virtual int? PhotoId { get; set; }
}