global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kestrel_servers'
    static_configs:
      - targets: ['192.168.1.195:80', '192.168.1.95:80', '192.168.1.138:80']
  
  - job_name: 'nginx_exporter' # Load balancer
    static_configs:
      - targets: ['192.168.1.97:9113']
  
  - job_name: 'mssql'
    static_configs:
      - targets: ['192.168.1.122:4000']