name: push container image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push-image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./GotorzApp/
          push: true
          tags: |
            ghcr.io/ren3mh/t14gotorz/gotorzapp:latest
          build-args: |
            APPSETTINGS_JSON_BASE64=${{ secrets.APPSETTINGS_JSON_BASE64 }}


